### ISSUE TITLE
Example code doesn't seem to work

### ISSUE THREAD

**Issue by millerjoey** [trappmartin/HilbertSchmidtIndependenceCriterion.jl#2]
The `(value,threshold)` is `(0.0, NaN)` when I run the example in Julia version 1.1.0.

**Comment by trappmartin** [comment]
I'll have a look into this. Thanks for reporting!

**Comment by trappmartin** [comment]
Ok, there seems something strange going on. I'll try to fix it asap. I also messed up the example as the implementation is only for matrices and the example uses vectors of samples. I added an assertion so that people don't run into this.

I'll let you know ones I found the bug.

**Comment by millerjoey** [comment]
I think there was some row vs. column inconsistency. The examples were matrices of size (1,100), but M is size(X)[1] causing the bug. Meanwhile pairwise() by default goes along dims = 2, so we have to override that for if you want the input to be an e.g. (100,1) column vector.
